---
title: "installation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# はじめに
## R とは
Rは統計・データ解析・統計グラフ作成のためのオープンソースソフトである.

https://ja.wikipedia.org/wiki/R%E8%A8%80%E8%AA%9E

## R のインストール
Rをインストールするには

https://cran.r-project.org/

にいき, 該当機種のファイルをダウンロードする.
ダウンロードしたあとに実行すればインストールされる.

Ubuntu なら `ppa` を使って導入してもよい.
```
sudo add-apt-repository ppa:marutter/rrutter
sudo apt-get update
sudo apt-get install r-base r-base-dev
```

## R の設定
設定ファイル `.Rprofile` をホームディレクトリに作成すれば, 設定を変更できる.
ホームディレクトリはユーザー名が `kenji` のとき, Windows なら通常
`C:\Users\kenji` である. バックスラッシュ `\` は $\yen$ と読み替えて頂きたい. 
最初は `.Rprofile` を特に作成しなくても大丈夫である.


## R の使い方
コマンドプロンプトから R を立ち上げるか, アイコンをダブルクリックすると, 
Rコンソールと言われる画面が現れる.
そこにコマンドを入力すると, その結果が直後に出力される.
終了には `q()` とする. 
作業ディレクトリを保存するかと聞かれたなNoを意味する `n` を選択する.

R はRコンソールから対話式にコマンドを入力していく方法と,
拡張子 `R` のスクリプトファイルを実行していくやり方がある.
実行履歴を記録するためにスクリプトファイルを作成していくやり方を推奨する.
編集中に `Ctrl + Enter` で該当行をRコンソールに送信することができる.

スクリプトファイル `project.R` を Rコンソールから実行するには,
```
source("project.R")
```
とすればよい.  
R外部のコマンドプロンプトから実行するには
```
Rscript project.R
```
とすればよい. PATHとかに注意しなければならない.

外部ファイルを導入する際やファイルを外部出力する際には, 現在の作業ディレクトリに気をつけなければならない.
現在の作業ディレクトリの場所はRコンソールから
```
getwd()
```
とすれば, 確認できる. Windows だと通常の表記と異なっていることに注意されたい.
作業ディレクトリの指定は以下のようにする.
```
setwd(PATH)
```
Windows のとき指定の仕方に注意が必要である.
たとえば作業ディレクトリが ``C:\Users\kenji\work\project` のとき,
```
setwd("C:/Users/kenji/work/project")
```
となる. バックスラッシュ `\` ($\yen$) を スラッシュ `/` に変更しなければならない.


## RStudio とは
R の統合開発環境 (IDE, Integrated Development Enviroment) である.
オープンソース版が存在する.

https://ja.wikipedia.org/wiki/R-Studio

## RStudio のインストール
オープンソース版のRStudio のインストールは

https://www.rstudio.com/products/rstudio/download/

にいき, 該当機種のファイルをダウンロードする.
ダウンロードしたあとに実行すればインストールされる.

Ubuntu ならサーバー版を導入するとよい.

https://www.rstudio.com/products/rstudio/download-server/

## RStudio の設定
メニューバーの [Tools] => [Global Options...] で設定を変更できる.



## RStudio の使い方
RStudio の使い方として日本語版がある.

https://github.com/rstudio/cheatsheets/raw/master/translations/japanese/rstudio-IDE-cheatsheet_ja.pdf

他にも

https://www.rstudio.com/resources/cheatsheets/

幾つかのチートが存在する.

使い方の基本は基本的にソースコードを編集して実行させる.
編集中に `Ctrl + Enter` で該当行をRコンソールに送信することができる.

コンソールやコマンドラインで実行させるだけでなく,
実行結果をともなった html ファイルなどを生成できる.
メニューバーの [File] => [Knit Document...] で `HTML` を選択するとよい.

他にも word ファイル や pdf ファイル生成することも適切に設定していれば可能である.
さらに文章のなかに `R` コマンドを埋め込んだ `Rmd` ファイルを作成することができる

RStudio の場合, プロジェクトとして管理するとそこが自動的に作業ディレクトリになる.
メニューバーの [File] => [New Project...] で設定を変更できる.
すでにあるフォルダ (ディレクトリ) を選択できたり, あらたにディレクトリを作成できる.
またバージョン管理ソフトとも連携している.


外部データ入力がインタラクティブに実行可能である.
メニューバーの [File] => [Import Datasets...] で設定を変更できる.

